### ISSUE TITLE
Unable to figure out icons for paper-fab

### ISSUE THREAD

**Issue by paullewis** [PolymerElements/iron-icons#10]
I grabbed the `<paper-fab>`, and then I wanted an icon. It complained I didn't have the iron icons in the console (ace, love it), so I imported those. But then I couldn't find out which icons are in the iron set (vs any other set), so I went to https://elements.polymer-project.org/elements/iron-icons and that has no documentation.

Feels like we should have a list of icons, and where they come from.

**Comment by paullewis** [comment]
+cc @ebidel @robdodson @arthurevans

**Comment by arthurevans** [comment]
Yep. We're missing a few bits here. iron-icons actually has a demo that shows all the icons, but it's not getting linked up:

https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

**Comment by ebidel** [comment]
Dupe of https://github.com/PolymerElements/iron-icons/issues/13
