### ISSUE TITLE
Demo for iron-icon is two arrows

### ISSUE THREAD

**Issue by paullewis** [PolymerElements/iron-icons#11]
See https://elements.polymer-project.org/elements/iron-icon?active=iron-icon&view=demo:demo/index.html

cc @ebidel @arthurevans @robdodson

**Comment by notwaldorf** [comment]
I think the two arrows aren't the problem, but the fact that they're unlabelled. I'll add some descriptions :)

**Comment by paullewis** [comment]
Kinda. It feels like seeing a demo for icons should show something more akin to http://www.google.com/design/spec/style/icons.html#icons-system-icons

**Comment by notwaldorf** [comment]
But `iron-icon` is just the demo for how to use an icon. The entire list of icons is in the `iron-icons` demo (see: https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html).

**Comment by paullewis** [comment]
Okay, so maybe we just kind of surround the icon with something that says it's a demo for a single icon and that if you're looking for the whole set check out the `iron-icons` demo. I only flagged it because I spent some of my weekend trying to find the icons I could use with `<paper-fab>` and ended up being confused by both this and #10

**Comment by notwaldorf** [comment]
:+1: Sorry that this ate your time :(

**Comment by paullewis** [comment]
Haha it's no problem at all! Be weird if I didn't find anything on account of being easily confused.
