### ISSUE TITLE
Docs and demo for iron-icons are missing

### ISSUE THREAD

**Issue by davydik** [PolymerElements/iron-icons#13]
See
https://elements.polymer-project.org/elements/iron-icons

Docs page is empty
Demo is missing

**Comment by robdodson** [comment]
+1

**Comment by jurgenfink** [comment]
@davydik @robdodson  Yes, you are right. It seems, they are still working on the issue. We are sure that the Polymer Team will fix it soon, as the issue seems to be "only" a timing-issue . If you like, you may want to have a look at certain workarounds we came up with meanwhile:
[https://github.com/PolymerElements/iron-icon/issues/19](https://github.com/PolymerElements/iron-icon/issues/19) and [https://github.com/PolymerElements/iron-icons/issues/14](https://github.com/PolymerElements/iron-icons/issues/14) .

**Polymer Team**: keep up the good work - **Polymer rocks**, especially **1.0** :+1: 
And once *paper-sub-menu* and *paper-drop-down* are ready, **1.0** rocks even more, he he he
Good Luck and thanks to all of you.

**Comment by ebidel** [comment]
@atotic @garlicnation @tjsavage  how what do we need to do to get docs + demo of the icons? With the icon demo, it's impossible to know what's available.

**Comment by arthurevans** [comment]
Note that the demo is there, the docs are missing (and with them, the link to the demos).
In the case of iron-icons, this may be because we lack a tag for generic (non-element, non-behavior) components like iron-icons and iron-flex-layout.

**Comment by arthurevans** [comment]
Filed possibly-related issue here: https://github.com/PolymerElements/iron-doc-viewer/issues/47

**Comment by tjsavage** [comment]
`iron-icons` doesn't really fit our model for slurping element documentation into the catalog, which is no excuse not to show anything there but means it might take a little time to work out the best way to get documentation here. Arthur's issue above is the broader problem.

I'll keep this one open until we solve this one - thanks for everyone's patience!

**Comment by notwaldorf** [comment]
Assigning it to @tjsavage to keep an :eyes: on it. This probably requires a fix in `iron-component-page`, since the demo exists, but isn't showing up.

**Comment by atotic** [comment]
The problem is that iron-icons has no element to attach demo to. Until  https://github.com/Polymer/hydrolysis/issues/136 is fixed, your only workaround would be to create a dummy IconDemo @polymerBehavior, and attach @demo to it.

**Comment by miriti** [comment]
I couldn't wait so I've made my own catalog of the iron-icons :)
I'd like to share it with you: http://polymer-icons.polyploy.com/

**Comment by brianreeve** [comment]
For those looking for the "real" docs, this URL hack was presented in Polycast #20 as a workaround until it gets fixed:

https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

**Comment by kaycebasques** [comment]
The URL mentioned by @brianreeve no longer works (but I can verify that it used to).

**Comment by robdodson** [comment]
@kaycebasques it works for me? maybe the page was down for a bit?

**Comment by brianreeve** [comment]
@kaycebasques, @robdodson - I'm getting a generic 404 page apparently coming from Firebase at https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

Fairly certain it worked as recently as yesterday.

A cursory look at the other element docs exposes no other issues.

**Comment by kaycebasques** [comment]
Behavior I'm seeing is the same as described by @brianreeve.

**Comment by robdodson** [comment]
Hm that's weird. It's working fine for me in an Incognito window... @arthurevans @ebidel are you seeing similar issues?

**Comment by ebidel** [comment]
See it.
<img width="1023" alt="screen shot 2015-09-02 at 9 33 35 am" src="https://cloud.githubusercontent.com/assets/238208/9637471/d79abc70-5155-11e5-99fc-d74f6f14f0d9.png">

Is FB exploding?

**Comment by robdodson** [comment]
weird i'm in some kind of bubble it seems.

**Comment by ebidel** [comment]
Marking as code-yellow. It's been open for a while and doesn't make our docs look great.

**Comment by atotic** [comment]
Just created a showDocsDemo branch here that uses the polymerBehavior hack I mention above to display docs/demo. I think the old #hashlinks in the docs no longer work, other than that this is what I'd do for a quick fix.

**Comment by frankiefu** [comment]
I think requiring `<script>` tag with a behavior-like object following the comment is probably  unacceptable.  @garlicnation, how about adding support in hydrolysis, maybe something like this: https://github.com/Polymer/hydrolysis/issues/136

**Comment by garlicnation** [comment]
Fixed on a branch: http://polygit.org/hydrolysis*+:unattachedComments/iron-icons*+:pseudoElement/components/iron-icons/index.html

**Comment by frankiefu** [comment]
Sweet.  I will try it on Catalog to see if anything needs to be done there.

**Comment by arthurevans** [comment]
:100: :+1: :fireworks: :cake:

**Comment by phidias51** [comment]
This seems to be broken again.  There are currently no demos for the icons.
