### ISSUE TITLE
Easy To Fix: remove inline fill color in "track-changes" and "play-for-work" icons

### ISSUE THREAD

**Issue by d1manson** [PolymerElements/iron-icons#20]
Unlike the other icons in [`iron-icons.html`](https://github.com/PolymerElements/iron-icons/blob/master/iron-icons.html#L273), those two have `fill="#123"` inline which doesn't seem to be necessary and makes it difficult to change their color.  Simply removing this seems to do the trick I think.

**Comment by notwaldorf** [comment]
We are getting the icons automatically from the Material Design icon set. @azakus, do you think this is something that could be changed there?

**Comment by notwaldorf** [comment]
Closing, as we don't control the icons, and this bug should be filed on the Material Design repo instead (https://github.com/google/material-design-icons)
