### ISSUE TITLE
Update Icon Documentation

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/iron-icons#21]
The core-icons documentation had an icon showcase page [https://www.polymer-project.org/0.5/components/core-icons/demo.html} that showed each of the different icon sets and the icons available to them.  The current iron-icons element page has no documentation whatsoever, and is in desperate need of an update.  It would be good if the documentation was also searchable, to make it easier to find icons.

**Comment by fxedel** [comment]
There actually is a demo with all icons: https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

But it's not accessible when you search for `iron-icons` because there isn't the demo button. Maybe it's because there are still no docs for this element?

**Comment by notwaldorf** [comment]
This has already been fixed in the catalog.

**Comment by phidias51** [comment]
Thanks Monica.  I looked at the demo page and I noticed that all of the icon names were prefaced with "icons:*".  Is that now required or will the short name still work.

**Comment by notwaldorf** [comment]
For `icons:` the short name still works, but for all other collections, you need to use the prefix (`maps:local-pizza`)
