### ISSUE TITLE
[Request] File-related icons not found

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/iron-icons#22]
It would be useful if the file-related icons (seen in the Google Drive) application were also available as an iconset.  In particular, the document, spreadsheet, slides, (and their MS Office equivalents), and a PDF icon.

**Comment by notwaldorf** [comment]
@tjsavage @zgibson is this something the design team can help us with?

**Comment by tjsavage** [comment]
Possibly! The place to file this request would be here: https://github.com/google/material-design-icons/
