### ISSUE TITLE
Unable to display some icons

### ISSUE THREAD

**Issue by matrix818181** [PolymerElements/iron-icons#23]
I don't know why but I'm not able to display 'attach-file' and 'attach-money' icons. Within the demo it's working, but outside, no.

This is what my code look like :
`<iron-icon icon="attach-money"></iron-icon>`

Can someone help me ? Thx

**Comment by notwaldorf** [comment]
You need to include `iron-icons/editor-icons.html` file, as well as use the `editor:` prefix for the icons:
```html
<iron-icon icon="editor:attach-money"></iron-icon>
<iron-icon icon="editor:attach-file"></iron-icon>
```

Here's a JSBin that does this: http://jsbin.com/rubove/edit?html,output
