### ISSUE TITLE
icons don't appear in Firefox

### ISSUE THREAD

**Issue by azakus** [PolymerElements/iron-icons#28]
_From @datasynth on July 28, 2015 16:19_

These icons (at least) from the default and other sets don't appear in Firefox (39.0): 

event-seat, icons-b, flight-land, icons-d, flight-takeoff, gif, indeterminate-check-box, av:airplay, av:b, av:d, av:forward-10, av:forward-30, av:forward-5...and more...from the iron-icons demo page (and other usages). 

<img width="938" alt="screen shot 2015-07-28 at 12 16 32 pm" src="https://cloud.githubusercontent.com/assets/5359293/8936884/ea790f3a-3522-11e5-87b6-48cb0f8871cb.png">
<img width="941" alt="screen shot 2015-07-28 at 12 16 42 pm" src="https://cloud.githubusercontent.com/assets/5359293/8936885/ea7e22a4-3522-11e5-9bd0-505470464eb8.png">

_Copied from original issue: PolymerElements/iron-icon#31_

**Comment by azakus** [comment]
_From @notwaldorf on October 19, 2015 23:3_

This is a problem with the material design icon set. Turns out there's about 73 icons that use `<use xlink:href`, which isn't a thing we support, and needs to be fixed in the original sources.
/cc @azakus who's investigating

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/iron-icons/pull/45
