### ISSUE TITLE
About half of icons not showing in demo in Polymer Element Catalogue

### ISSUE THREAD

**Issue by WaverleyDesign** [PolymerElements/iron-icons#33]
The icons displayed in the demo for the iron-icons element in the Polymer Element Catalogue are being cut off just below the communications set. There's a large white space showing but nothing else. Had a quick look in the devtools but couldn't find any particular reason that the display CSS property is set to none.

**Comment by blasten** [comment]
@WaverleyDesign this seems to work well for me: https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html&active=iron-icons

**Comment by WaverleyDesign** [comment]
It's working for me now that I've updated my Chrome Canary to the latest version. That's kind of interesting.. 
Thanks for checking it out.
