### ISSUE TITLE
Request for paper icon expand arrow

### ISSUE THREAD

**Issue by dman777** [PolymerElements/iron-icons#34]
This a request for a paper icon expand arrow that is used in Google Design's examples for cards. 

![arrow](https://cloud.githubusercontent.com/assets/887815/11022638/a172f49c-865b-11e5-9880-e0971fab1bf2.png)

**Comment by notwaldorf** [comment]
This looks the same as `hardware:keyboard-arrow-up`: https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html, so I don't think a new element is needed.
