### ISSUE TITLE
Material design icons 2.1.1

### ISSUE THREAD

**Issue by Krazitchek** [PolymerElements/iron-icons#41]
Material design icons has been updated with lot of new icons i don't see in actual iron-icons/demo.
Material design icons: https://github.com/google/material-design-icons/releases

Have you planed to update iron-icons ?

Thanks.

**Comment by mib4fun** [comment]
:+1:

**Comment by notwaldorf** [comment]
Thanks! I'll take a look tonight or tomorrow!

**Comment by MaxRoecker** [comment]
:+1:
