### ISSUE TITLE
Minify?

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-icons#43]
Has anyone tried running the icons sets through an SVG minifier?  It's more difficult to run these things through a minifier after-the-fact because everything is wrapped up in HTML.

I tried a few SVG minifiers by copying and pasting the `<svg>` but they all chocked on the "xlinks" (`Error in parsing: Unbound namespace prefix: "xlink"`).  One claimed a 30% reduction in size without any loss in precision, but it looked the some of the markup was missing.

**Comment by ebidel** [comment]
The xlinks are a known issue from the imported material design icons. We're working on it in https://github.com/PolymerElements/iron-icons/issues/28#issuecomment-149372961.

**Comment by notwaldorf** [comment]
I think the xlinks should be gone now. Closing, but please re-open this issue if it still occurs.
