### ISSUE TITLE
Missing/corrupt icons

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-icons#44]
Some in the default icon set are missing/corrupt: `icons:b`, `icons:a`, etc

<img width="600" alt="screen shot 2015-12-19 at 4 40 55 pm" src="https://cloud.githubusercontent.com/assets/238208/11915900/53d87e08-a66f-11e5-9ed8-00a0ca9a1f8d.png">

**Comment by ebidel** [comment]
@notwaldorf @azakus

**Comment by notwaldorf** [comment]
Duplicate of https://github.com/PolymerElements/iron-icons/issues/28

The problem is that the icons from the Material Design repo use an unsupported `xlink:href`. There's another issue open that there's new icons available, so I'll run the script tonight and see if they've also fixed these ones.
