### ISSUE TITLE
--layout-flex-1 mixin used iron-flex-layout doesn't provide it

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/iron-icons#54]
https://github.com/PolymerElements/iron-icons/blob/master/demo/index.html#L84 uses `--layout-flex-1` but iron-flex-layout only provides `--layout-flex-2` to `--layout- `--layout-flex-12`. Is this a bug or do I miss something?

**Comment by notwaldorf** [comment]
Yup, looks like a bug! I think it should probably just be `layout-flex`. Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by zoechi** [comment]
Sorry, I use only Dart and try to avoid the effort setting a JS environment up where I can run tests and probably other things necessary.

**Comment by notwaldorf** [comment]
No worries! Maybe somebody else will take a look :)
