### ISSUE TITLE
Material Design Icons 2.2.0 is out

### ISSUE THREAD

**Issue by Krazitchek** [PolymerElements/iron-icons#56]
Material design icons 2.2.0 has been updated with 41 new icons.
Material design icons: https://github.com/google/material-design-icons/releases

Thanks. :-)

**Comment by abdonrd** [comment]
:+1:

**Comment by dantman** [comment]
When will this be fixed? This is "the" way to use Material Icons with Polymer and I wanted to use the delete forever icon.

**Comment by bennyp123** [comment]
I'd like to contribute to fixing this issue and updating to 3.0.1.

**Comment by notwaldorf** [comment]
If someone want to send a PR for this, it would be great -- all you have to do is run the `update-icons.sh` script in this repo.

**Comment by bennyp123** [comment]
I sent in PR #63

**Comment by bennyp123** [comment]
https://github.com/PolymerElements/iron-icons/pull/65/commits/551f1c44c20df1d4299f04825b4aba0920701c48 replaces `@license` string
