### ISSUE TITLE
Iron icons in chrome do not work

### ISSUE THREAD

**Issue by erinhong17** [PolymerElements/iron-icons#63]
Some icons (seems to be the icons under the "icons:" set of icons whereas icons in "communications:" work) 
In the chrome inspect tool, the icon is detectable but is not visible. 
### DOES NOT work on Chrome

Version 51.0.2704.79 (64-bit) on Mac Book Pro OS X El Captain Version 10.11.4
### DOES work on Safari

Version 9.1 (11601.5.17.1)
### Expected Results:
- no error is thrown 
- icon will be present but svg is not generated 
### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

**Comment by notwaldorf** [comment]
Can you provide a screenshot? Here's the iron-icons [demo](https://elements.polymer-project.org/elements/iron-icons?active=iron-iconset-svg&view=demo:demo/index.html) on my Chrome 51.0.2704.103 on 10.11.6:

<img width="1275" alt="screen shot 2016-08-02 at 5 30 30 pm" src="https://cloud.githubusercontent.com/assets/1369170/17349933/e6c999e4-58d6-11e6-9ec6-5096c82868b6.png">

It's super zoomed out to get as many of them in, but they're all there.

**Comment by erinhong17** [comment]
@notwaldorf I can see them all on the demo, I should have clarified. I downloaded the app demo template, started to play around with the icons until I noticed that some showed up and some dont! So I noticed that "icons:menu" works perfectly fine.. and if I swap out that icon for another one such as "icons:gesture" or "icons:check" or many others within the "Icons" library, they just don't show up. 

My current Chrome version: Version 51.0.2704.106 (64-bit) on 10.11.4

As mentioned earlier, detectable in the Chrome inspect tool: 

Image below is where the search icon is not there but the filter shows up! 
This happens in my own custom components as well as the demo project that is usable from the polymer-project website.  

![image](https://cloud.githubusercontent.com/assets/19808836/17372953/ef97cb66-595a-11e6-800a-864ef801e3c7.png)

**Comment by notwaldorf** [comment]
I think there might be something wrong in your demo. Here's a jsbin where the icons show up fine in Chrome: http://jsbin.com/sokaza/edit?html,output

<img width="99" alt="screen shot 2016-08-03 at 10 37 02 am" src="https://cloud.githubusercontent.com/assets/1369170/17375542/3b28de16-5966-11e6-860c-782977853b14.png">

If you can provide a similar JSBin with your repro steps that would be great

**Comment by Moggers** [comment]
I ran into the same issue (can render arrow-back, menu, chevron-right, and close, but no others). The app-drawer demo imports my-icons.html which is a locally defined very slim subset of iron-icons. If it comes after the import iron-icons I believe it overwrites the config? So if you try to go from the out of the box template and import iron-icons you seem to end up just having it overwritten by my-icons.html.

**Comment by Asoseil** [comment]
With the starter project "my-icons.html" overwrite the import of iron-icons

**Comment by SecareLupus** [comment]
I was having the same problem, and can confirm that swapping the order of the imports of my-icons and iron-icons fixed the issue for me. I was using the polymer init project as a base, presumably OP is too?

**Comment by tony19** [comment]
The iconset name conflict is fixed in https://github.com/PolymerElements/polymer-starter-kit/issues/934

**Comment by arthurevans** [comment]
As @tony19 said, this appears to be a PSK issue that's now fixed in PSK. Closing here.
