### ISSUE TITLE
is there any icon for json format symbol - { }

### ISSUE THREAD

**Issue by Nagasai-Aytha** [PolymerElements/iron-icons#76]
Hi 

I was looking for json format icon 

something similar to [http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/high-resolution-dark-blue-denim-jeans-icons-alphanumeric/072287-high-resolution-dark-blue-denim-jeans-icon-alphanumeric-bracket-curley.png]

I am tried below workaround but it didnt work either

` <paper-icon-button id="json">{}</paper-icon-button>`

https://codepen.io/nagasai/pen/rwqYYZ

Thanks
Sai

**Comment by web-padawan** [comment]
Here you go: https://vaadin.com/icons#curly-brackets

**Comment by Nagasai-Aytha** [comment]
Solution:
src property of <paper-icon-button> web component will allow to create custom icon

<paper-icon-button src="http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/high-resolution-dark-blue-denim-jeans-icons-alphanumeric/072287-high-resolution-dark-blue-denim-jeans-icon-alphanumeric-bracket-curley.png"></paper-icon-button>
