### ISSUE TITLE
iron-icons other than default iron-icons are not displayed on polymer 3

### ISSUE THREAD

**Issue by sumioka** [PolymerElements/iron-icons#94]
### Description

maps icons or communication icons are not displayed

### Expected outcome
maps icons like maps:place are to be displayed on 

### Actual outcome
maps icons are not displayed on polymer 3.  
there is no code in build folder about maps etc. there is only js file for default icons.

### Live Demo
no demo

### Steps to reproduce
if someone can display, my problem is to be ignored.

### Browsers Affected

- [o] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by sumioka** [comment]
when I write the another img tag, one of the icons are displayed. one map icon is displayed, another map icon remains undisplayed

**Comment by sumioka** [comment]
reproduce condition is not clear, so temporally close this issue.

**Comment by sumioka** [comment]
I wrote the <img src="images/home.png" id="2"> then

<a images="" home.png"="" id="1" href="http://....&gt;&#10;                &lt;img src=">
                <img src="images/home.png" id="2">
                
              </a>

**Comment by sumioka** [comment]
sorry this might not be iron-icons probrem. I check it more precisely

**Comment by GrantASL19** [comment]
For us the solution to this problem was to import the required icon sets.

Before:

```js
import '@polymer/iron-icons/iron-icons.js';
```

After

```js
import '@polymer/iron-icons/iron-icons.js';
import '@polymer/iron-icons/social-icons';
```
